site_name: COMP423 Course Notes
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - search.highlight
    - search.suggest
  palette:
    primary: blue
    accent: light-blue

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Tutorials:
    - Setting up a dev container for Go: tutorials/go-setup.md